### ISSUE TITLE
IndexError when 'return_images' or 'return_moments' are set to True

### ISSUE THREAD

**Issue by astropatel** [esa/tetra3#10]
Hello Gustav,

There appears to be an IndexError that is raised when the kw_args 

`return_images`  
`return_moments` 

are set to True.  When these are `False` , the `centroids` in `solve_from_image` comes out to be an Nx2 array of N star centroids. When this is passed to `solve_from_centroids`, the line `star_centroids[:num_stars,:]` works perfectly. However, when those two keywords are set to True, a 3 element tuple is passed which throws an IndexError when  `star_centroids[:num_stars,:]` tries to slice `star_centroids`.

**Comment by gustavmpettersson** [comment]
If `return_moments=True` and/or `return_images=True` in `get_centroids_from_image` the centroids are returned in the first position of a tuple together with the extra return data requested. This is specified in the documentation

**Comment by astropatel** [comment]
Yes, I understand. But if those return_moments and return_images are set to True, the code doens't seem to be handling the propagation correctly. If I run test_tetra3 as is, it runs perfectly. 

But if I include those keywords, the error persists:
![image](https://github.com/esa/tetra3/assets/3648312/b65f637f-c003-4a0d-99c1-4e586d8d6df8)
![image](https://github.com/esa/tetra3/assets/3648312/d7f86966-9bb6-48ed-bc4b-56205b4de2d3)

**Comment by gustavmpettersson** [comment]
Thanks for the note. Those arguments are not intended to be supported in `solve_from_image`, we will clarify this in the documentation. If you want to see more into the centroiding please use `get_centroids...` and `solve_from_centroids`

**Comment by gustavmpettersson** [comment]
FYI, this was now implemented anyway, so extra return values are passed through from `get_centroids_from_image`
