### ISSUE TITLE
Package structure for installation

### ISSUE THREAD

**Issue by alexw-im** [esa/tetra3#14]
Typically, to use a package-under-development, I'd `pip install -e git+https://github.com/somerepo/repo.git`

However, this repo at present doesn't include a `setup.py`, nor does it include (or have the directory structure for) a `pyproject.toml`, so `pip install -e` won't succeed.

For now I've worked around it by adding my own trivial setup.py:

```python
from setuptools import setup, find_packages

setup(
    name='tetra3',
    version='0.1',
    packages=find_packages()
)
```

However it'd be an improvement for newcomers to add one or the other of those two setup avenues so the library can be installed in a location separate from the project.

**Comment by gustavmpettersson** [comment]
Hi @alexw-im, we're working on getting a proper package structure in the `package_prep` branch. Feel free to use that for now and suggest any improvements. We'll discuss the work in PR https://github.com/esa/tetra3/pull/15

**Comment by gustavmpettersson** [comment]
This has been merged to master, please let me know if tou have any issues

**Comment by alexw-im** [comment]
I blindly merged that PR into my own main branch and have been using it since, so consider that an unscientific thumbs up.

Thanks for the attention!
