### ISSUE TITLE
"Roll relative to north celestial pole" clarification

### ISSUE THREAD

**Issue by bribrah** [esa/tetra3#4]
I am a bit confused about what the roll results signify on the solve image results, it does not seem to be a standard astronomical measurement.

Thanks,

**Comment by gustavmpettersson** [comment]
Hi Brian,

This is the rotation of the image around the boresight axis, so it does not signify anything regarding the pointing direction. 

I haven't looked at this in a long time, but believe 0 rotation is when the "upwards" direction of the image points to the (celestial) North, with rotation measured clockwise from there. 

Gustav

**Comment by bribrah** [comment]
When u say upwards direction of the image do you mean like upwards in the y direction of the 2d xy image? Or do you mean like up in 3d space, ie, if I have an image pointed where the middle was directly at the north celestial pole, the roll would be 0.

**Comment by gustavmpettersson** [comment]
Yes, upwards as in the -Y direction of the image. (Negative since the Y=0 is the first row of a 2D image). If you point perfectly at the North celestial pole the roll would be undefined.
