### ISSUE TITLE
Algorithm used for hash code generation

### ISSUE THREAD

**Issue by han-k59** [esa/tetra3#5]
From the Tetra3 documentation the hash code generation is described as follows:

> Each pattern is made up of four stars, and the fingerprint is created by calculating the distances between every pair of stars in the pattern and normalising by the longest to create a set of five numbers between zero and one. This information, and the desired tolerance, is used to find the indices in the database where the match may reside by a hashing function.

This is the same as described in the ASTAP solver documentation of 2018, see flowchart:
https://www.hnsky.org/astap_astrometric_solving.htm

Is this coincidence or did we find independent the same technical solution?

Han

**Comment by gustavmpettersson** [comment]
Hi Han,

This pattern was implemented in the original version by brownj4 around 2016, I don't know the origins further than that. My guess would be a coincidence.

Gustav
