### ISSUE TITLE
star_catalog_IDs issue

### ISSUE THREAD

**Issue by astropatel** [esa/tetra3#9]
Dear Gustav,

   I'm trying to generate my own database using a fake star catalog. I pulled a version of tetra3 about a month ago, and I was able to generate a database using my list of stars (though finding a solution has been NaNs thus far). In any case, I pulled the latest version with the new star_catalog_IDs property and when I try to load the new database into a new instatition of tetra3, I run into a ValueError concerning pickle files. I've changed the code a bit to include my new test catalog and tried to incorporate the star_catalog_IDs as best as possible -- but am wondering if that property is necessary to the overall function of the calculation?

![image](https://github.com/esa/tetra3/assets/3648312/61a3d166-e6fc-431e-8c90-0ae25128a04c)

**Comment by gustavmpettersson** [comment]
Hi,

Could you upload this database somewhere for me to look at? (Or a small one with the same behaviour)

To be clear
- The database you are loading, was it built with the latest version or the older one?
- To load the database, were you using the latest version or the older one?

It's possible that this is from an old bug where we would store a None in the star_catalog_IDs, making them unable to be unpacked without pickle, but that should not be there anymore.

**Comment by astropatel** [comment]
I'm uploading the database as well as the version of the code I'm using (with the changes i've made) and a test image..

The database was built and loaded using the latest version. In the new one, it's having issues with the pickle error. In the old and new one, I get a bunch of nan's when trying to use solve_from_image.


[rahul_tetra3.zip](https://github.com/esa/tetra3/files/12255317/rahul_tetra3.zip)
st version.

**Comment by gustavmpettersson** [comment]
Without looking in detail, it appears that you are using 'str' type for the star catalogue ID. This cannot be used in a np archive without pickling. You need to make the ID a native np type, e.g. U16 for a 16 byte char array

**Comment by astropatel** [comment]
That fixed it! Thank you. I am still having a problem with obtaining solutions from my test images.

**Comment by gustavmpettersson** [comment]
Great.

I don't know what you are trying to do, but at least these things need to be true for it to work:
- The database you use to build the catalogue needs to have at least 20 stars per FOV.
- The FOV selected when building the database needs to match the FOV of your test images.
- The centroids need to be correctly extracted from the test images.
- The test images need to be correctly projected (not distorted).
